{
  "formatVersion": "1.1",
  "component": {
    "url": "../../dm-interpreter/0.11.0/dm-interpreter-0.11.0.module",
    "group": "io.github.mbackschat.a12.dm",
    "module": "dm-interpreter",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "dm-interpreter-js-0.11.0.klib",
          "url": "dm-interpreter-js-0.11.0.klib",
          "size": 1639724,
          "sha512": "43d6228fe71ceefad79ac66f594d895d1096b65986a4ccb8c7a0794062efb9b99130b2a4db9a2cb8eaf65ab978c1f88272c0326ba84b74321483f8bac3ab28ca",
          "sha256": "4a43962c6ea9cef505d80257e62aca739b52a892e0dd82d72f28be0c004c0a82",
          "sha1": "2d8a25f4e2cf20d9f1de31c64e0bcbe27d163047",
          "md5": "ccfe1651ebb7678969cf94eeaafbbed3"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "dm-interpreter-js-0.11.0.klib",
          "url": "dm-interpreter-js-0.11.0.klib",
          "size": 1639724,
          "sha512": "43d6228fe71ceefad79ac66f594d895d1096b65986a4ccb8c7a0794062efb9b99130b2a4db9a2cb8eaf65ab978c1f88272c0326ba84b74321483f8bac3ab28ca",
          "sha256": "4a43962c6ea9cef505d80257e62aca739b52a892e0dd82d72f28be0c004c0a82",
          "sha1": "2d8a25f4e2cf20d9f1de31c64e0bcbe27d163047",
          "md5": "ccfe1651ebb7678969cf94eeaafbbed3"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "dm-interpreter-js-0.11.0-sources.jar",
          "url": "dm-interpreter-js-0.11.0-sources.jar",
          "size": 434703,
          "sha512": "d3fbc40d428c41c14df26418dda928889aa3b82c1802a543d4d205afe3a493faf02b339474917d269ca792bbd3e459d242808287ef749fd0af4dc487bc641a5e",
          "sha256": "b2391f52070b1d8fbb7d1cbf43e31bf5bee3ed495266cefd7a2cddf88e531f5b",
          "sha1": "d2431d972e2ee544f72a22d8407e57df9cd26ac2",
          "md5": "a0041609c4401abc42698344891b43d0"
        }
      ]
    }
  ]
}
