{
  "formatVersion": "1.1",
  "component": {
    "url": "../../dm-interpreter/0.10.0/dm-interpreter-0.10.0.module",
    "group": "io.github.mbackschat.a12.dm",
    "module": "dm-interpreter",
    "version": "0.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "dm-interpreter-jvm-0.10.0.jar",
          "url": "dm-interpreter-jvm-0.10.0.jar",
          "size": 1483774,
          "sha512": "c184f9c060e08c17b42102035e959b054f1fbfae8526d6e072984cd612871ad2e4f18a4685c560645d7995a7a2f5a4ac672b9691d014021df720c28742763790",
          "sha256": "7a1e9ae20091210f6e50f473330277884af83c181a1047b8c1450edf6ca627a1",
          "sha1": "f6bb23855f201cac3ba66a993f1daaf774962c26",
          "md5": "ffa4791dd60ed138414f1036da54c81a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "dm-interpreter-jvm-0.10.0.jar",
          "url": "dm-interpreter-jvm-0.10.0.jar",
          "size": 1483774,
          "sha512": "c184f9c060e08c17b42102035e959b054f1fbfae8526d6e072984cd612871ad2e4f18a4685c560645d7995a7a2f5a4ac672b9691d014021df720c28742763790",
          "sha256": "7a1e9ae20091210f6e50f473330277884af83c181a1047b8c1450edf6ca627a1",
          "sha1": "f6bb23855f201cac3ba66a993f1daaf774962c26",
          "md5": "ffa4791dd60ed138414f1036da54c81a"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dm-interpreter-jvm-0.10.0-sources.jar",
          "url": "dm-interpreter-jvm-0.10.0-sources.jar",
          "size": 404910,
          "sha512": "703c36ba7478fcad8610ecb8da999fa6c1e2f38376d4cbabcfc3d89a2a4a79c1244d55144f4f18da9fb6337c05a03dd7e787e2ca449068876afcb4aa7bf4d572",
          "sha256": "cb4e2af1ab4a17ac2f31b932de08e044ba6591b73f533fff0d280ee91ff70495",
          "sha1": "b371a88b655b1eddf44ecb382bc71d5f86710dbb",
          "md5": "c3612046bd1613c0b051328211065c75"
        }
      ]
    }
  ]
}
