{
  "formatVersion": "1.1",
  "component": {
    "url": "../../dm-interpreter/0.9.1/dm-interpreter-0.9.1.module",
    "group": "io.github.mbackschat.a12.dm",
    "module": "dm-interpreter",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "dm-interpreter-js-0.9.1.klib",
          "url": "dm-interpreter-js-0.9.1.klib",
          "size": 1506642,
          "sha512": "66c5244efa68c650907ae4c8689149ace2c2daf12c0fc760898835e9095c903a868c040918cbc0ac0978b0e3d4684982881dfb0672f4f1862224529afc4d886e",
          "sha256": "80b63970535cd08b3746671248757e14b6c451f8f0f777d160a1af660e325de9",
          "sha1": "f99ed52126f3f9665f9579dcc0971cb80c42f3ce",
          "md5": "750a12d398e8c2d4b78d1feff7fdc332"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "dm-interpreter-js-0.9.1.klib",
          "url": "dm-interpreter-js-0.9.1.klib",
          "size": 1506642,
          "sha512": "66c5244efa68c650907ae4c8689149ace2c2daf12c0fc760898835e9095c903a868c040918cbc0ac0978b0e3d4684982881dfb0672f4f1862224529afc4d886e",
          "sha256": "80b63970535cd08b3746671248757e14b6c451f8f0f777d160a1af660e325de9",
          "sha1": "f99ed52126f3f9665f9579dcc0971cb80c42f3ce",
          "md5": "750a12d398e8c2d4b78d1feff7fdc332"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "dm-interpreter-js-0.9.1-sources.jar",
          "url": "dm-interpreter-js-0.9.1-sources.jar",
          "size": 385356,
          "sha512": "7c273a5f5500296e81c895867c0b6ef6d76c61b0956542700c782149998f08c424c9432c6d62eb07e23852ec63c840c0e87d7e4bbebdf319df85700fcdee3ff7",
          "sha256": "7863a08f5d630a5f1c05acfdf36be47ef56f1da2388b943d7f7e7bd2f524caf6",
          "sha1": "95cf336cc8e70a22c69fe06ff73ed64fde85ac7f",
          "md5": "d525aa61a8cba90a38e98152ae56c0f0"
        }
      ]
    }
  ]
}
