{
  "formatVersion": "1.1",
  "component": {
    "url": "../../dm-interpreter/0.10.0/dm-interpreter-0.10.0.module",
    "group": "io.github.mbackschat.a12.dm",
    "module": "dm-interpreter",
    "version": "0.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "dm-interpreter-js-0.10.0.klib",
          "url": "dm-interpreter-js-0.10.0.klib",
          "size": 1572705,
          "sha512": "c0d88e8d7327518a67f88dc3d901cb9508bdd9a158090cfce28313c517f76f0ab4dc333aea6e2922751f992fc528826ef2059a774a5880e1465bd9ca5288ac0d",
          "sha256": "ba58349a8bca1488e44a45c643bbab9852965a9a295f225f3b80d1338f3c09f9",
          "sha1": "9c94b35953909652a82a17983959583bae5a1268",
          "md5": "07dc198188d659b3d2d22678369feedd"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "dm-interpreter-js-0.10.0.klib",
          "url": "dm-interpreter-js-0.10.0.klib",
          "size": 1572705,
          "sha512": "c0d88e8d7327518a67f88dc3d901cb9508bdd9a158090cfce28313c517f76f0ab4dc333aea6e2922751f992fc528826ef2059a774a5880e1465bd9ca5288ac0d",
          "sha256": "ba58349a8bca1488e44a45c643bbab9852965a9a295f225f3b80d1338f3c09f9",
          "sha1": "9c94b35953909652a82a17983959583bae5a1268",
          "md5": "07dc198188d659b3d2d22678369feedd"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "dm-interpreter-js-0.10.0-sources.jar",
          "url": "dm-interpreter-js-0.10.0-sources.jar",
          "size": 413451,
          "sha512": "b5a73b959bbb96bf65bcaffc0c4a521173e0f3d31e7eae11dc04ee457d71aadeac5c1637cf8c7130bb84e171cd7f4634e5af7744bb603eaa3911610c695afb2e",
          "sha256": "2f57cf0d30fc589ecec0bb3f81776da712f4ea5692eb58cc09aca27ce9f80513",
          "sha1": "ed5ad119ea958f4b7dc265329d273fd6027eea66",
          "md5": "c65312d2cc088279fdc01ada8a9f8d76"
        }
      ]
    }
  ]
}
