{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mbackschat.a12.dm",
    "module": "dm-interpreter",
    "version": "0.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "dm-interpreter-metadata-0.12.0.jar",
          "url": "dm-interpreter-0.12.0.jar",
          "size": 137713,
          "sha512": "7581efb236d188d9cd24a6a1904421098f2610cbe62848a5eacd29512b20528c588dc5ee3d73d2b4c5f1497bba4bd6c557f6f67b99fef8de2c7d52f76b28ef97",
          "sha256": "5002f7f19b9a8ce1404a62d40321ac55f0c15779240c242a3a4ad0b9cbcc049e",
          "sha1": "f51fcbe213766fb04ae2368bb32b69881b342f7f",
          "md5": "57a461a357e34f931d3db472c94bf0a4"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "dm-interpreter-kotlin-0.12.0-sources.jar",
          "url": "dm-interpreter-0.12.0-sources.jar",
          "size": 429077,
          "sha512": "3bd3e923fa346a64f944caac82993243066c6f2c59d826d93dfa3bcb9787b7109e0b8feefb6da4ef12e50368bef21e7c3c3e2a41df971b157df83dd9ad8e7961",
          "sha256": "45705c1131e11fe05579db1fc24bdc7e342b47a85081e506718c38de068c62e2",
          "sha1": "3cf94f508d2646f175f0c176d077df334be69c97",
          "md5": "7af9eb0d09f5a1b64a7751927ac46999"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../dm-interpreter-js/0.12.0/dm-interpreter-js-0.12.0.module",
        "group": "io.github.mbackschat.a12.dm",
        "module": "dm-interpreter-js",
        "version": "0.12.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../dm-interpreter-js/0.12.0/dm-interpreter-js-0.12.0.module",
        "group": "io.github.mbackschat.a12.dm",
        "module": "dm-interpreter-js",
        "version": "0.12.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../dm-interpreter-js/0.12.0/dm-interpreter-js-0.12.0.module",
        "group": "io.github.mbackschat.a12.dm",
        "module": "dm-interpreter-js",
        "version": "0.12.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../dm-interpreter-jvm/0.12.0/dm-interpreter-jvm-0.12.0.module",
        "group": "io.github.mbackschat.a12.dm",
        "module": "dm-interpreter-jvm",
        "version": "0.12.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../dm-interpreter-jvm/0.12.0/dm-interpreter-jvm-0.12.0.module",
        "group": "io.github.mbackschat.a12.dm",
        "module": "dm-interpreter-jvm",
        "version": "0.12.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../dm-interpreter-jvm/0.12.0/dm-interpreter-jvm-0.12.0.module",
        "group": "io.github.mbackschat.a12.dm",
        "module": "dm-interpreter-jvm",
        "version": "0.12.0"
      }
    }
  ]
}
